version: '2'

services:
  web:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # static files of api silex skeleton
      - .:/var/www/html/
      # nginx custom configs
      - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: sacredskull/php-7-fpm-development
    volumes:
      # php files
      - .:/var/www/html/
      # php custom configs
      - ./config/docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/docker/php/php-fpm.d/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./config/docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/docker/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    extends:
      file: ./config/docker/envs/develop.yml
      service: php
    links:
       - apidb

  apidb:
    image: mysql:5.7
    ports:
       - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
